// Generated by scripts/build-core.mjs; identifies the executed decoder artifacts.
export const decoderDiagnosticBuild={"coreHash":"9981edae90bf49bcdd82e8d1cdeba8a2b1a9a8eb7dc146e8f87c28b0672a0a90","framingHash":"77f1581d0169ae14f2ac4aa3be86ed821978e9bc520c24696e6ae8f48b034fb0"} as const;
