import type {DecodedFrameData, ObjectEvent} from './index.js';
// Generated by scripts/build-mpegh.mjs.
// @ts-ignore
import createModule from '../pkg-mpegh/mpegh.js';
// @ts-ignore
import wasmUrl from '../pkg-mpegh/mpegh.wasm?url';
let runtime: any;
let loading: Promise<void> | undefined;
export function initMpegh(): Promise<void> {
  return loading ??= createModule({locateFile: () => wasmUrl}).then((m: any) => {runtime=m;});
}
export function isMhas(data: Uint8Array): boolean {return data[0]===0xc0&&data[1]===1&&data[2]===0xa5;}
/** Do not enter the stateful decoder until a complete audio AU is buffered. */
function mhasAccessUnit(bytes:Uint8Array,start:number):number {
  let bit=start*8;
  const get=(n:number)=>{if(bit+n>bytes.length*8)throw 0;let v=0;while(n--)v=v*2+((bytes[bit>>3]!>>(7-(bit++&7)))&1);return v;};
  const escaped=(a:number,b:number,c:number)=>{let v=get(a);if(v===2**a-1){const w=get(b);v+=w;if(w===2**b-1)v+=get(c);}return v;};
  try{while(bit<bytes.length*8){const type=escaped(3,8,8);escaped(2,8,32);const length=escaped(11,24,24);if(length>1024*1024)throw Error('MPEG-H packet too large');if(bit%8)throw Error('MPEG-H unaligned packet');bit+=length*8;if(bit>bytes.length*8)return 0;if(type===2)return bit/8;}}catch(e){if(e!==0)throw e;}
  return 0;
}
const CICP_LABELS:Record<number,string>={0:'L',1:'R',2:'C',3:'LFE',4:'Ls',5:'Rs',6:'Lc',7:'Rc',8:'Lb',9:'Rb',10:'Cb',13:'Ls',14:'Rs',15:'Lw',16:'Rw',17:'Tfl',18:'Tfr',19:'Tfc',20:'Tbl',21:'Tbr',22:'Tbc',23:'Tsl',24:'Tsr',25:'Tc',26:'LFE',30:'Tbl',31:'Tbr',32:'Tfl',33:'Tfr',41:'Lb',42:'Rb'};
/** MHAS packet header, ISO/IEC 23008-3 escapedValue syntax. */
export function mhasPacket(type:number,payload:Uint8Array):Uint8Array {
  const bits:number[]=[];
  const put=(v:number,n:number)=>{for(let i=n-1;i>=0;i--)bits.push((v>>>i)&1);};
  const escaped=(v:number,a:number,b:number,c:number)=>{const max=2**a-1;put(Math.min(v,max),a);if(v>=max){v-=max;const m=2**b-1;put(Math.min(v,m),b);if(v>=m)put(v-m,c);}};
  escaped(type,3,8,8);escaped(1,2,8,32);escaped(payload.length,11,24,24);
  const result=new Uint8Array(bits.length/8+payload.length);
  bits.forEach((b,i)=>result[i>>3]!|=b<<(7-(i&7)));result.set(payload,bits.length/8);return result;
}
export class MpeghDecoder {
  discardBeforeSeconds = 0;
  private pending=new Uint8Array(0);
  private frames:DecodedFrameData[]=[];
  private samplePos=0;
  private dead=false;
  constructor(private rawAu=false,config?:Uint8Array,private referenceOnly?: (channels: Float32Array[], sampleRate: number) => void, private emitSourcesWithReference=false){
    if(!runtime)throw Error('MPEG-H runtime not initialized');
    const error=runtime._sda_open(0);if(error)throw Error(`MPEG-H create: ${(error>>>0).toString(16)}`);
    if(rawAu){if(!config?.length)throw Error('MPEG-H mha1 track is missing mhaC configuration');this.feed(mhasPacket(1,config));}
  }
  push(bytes:Uint8Array):void{this.feed(this.rawAu?mhasPacket(2,bytes):bytes);}
  private feed(bytes:Uint8Array):void {
    if(this.dead)throw Error('MPEG-H decoder closed');
    const joined=new Uint8Array(this.pending.length+bytes.length);joined.set(this.pending);joined.set(bytes,this.pending.length);
    let cursor=0;
    while(cursor<joined.length){
      const end=mhasAccessUnit(joined,cursor);if(!end)break;
      const n=end-cursor;
      if(n>runtime._sda_capacity())throw Error('MPEG-H access unit exceeds decoder capacity');
      runtime.HEAPU8.set(joined.subarray(cursor,cursor+n),runtime._sda_input());
      const err=runtime._sda_decode(n),used=runtime._sda_info(0);
      if(err===0x1000||err===0x1800){if(n===runtime._sda_capacity())throw Error('MPEG-H access unit exceeds decoder input capacity');break;}
      if(err)throw Error(`MPEG-H decode: 0x${(err>>>0).toString(16)}`);
      if(used<0||used>n)throw Error('MPEG-H invalid consumption');
      this.takeFrame();
      if(!used)break;
      cursor+=used;
    }
    this.pending=joined.slice(cursor);
    if(this.pending.length>1024*1024)throw Error('MPEG-H input stalled');
  }
  private takeFrame():void {
    const m=runtime, info=(k:number)=>m._sda_info(k);
    let n=info(3);if(!n)return;
    const objects=info(5),beds=info(6),hoa=info(7),rate=info(2);
    if(this.referenceOnly){
      const count=info(11),samples=info(10)/(count*3);
      if(count!==2 || !Number.isInteger(samples) || samples<=0)throw Error('MPEG-H invalid reference mix');
      const reference=[new Float32Array(samples),new Float32Array(samples)];
      const bytes=m.HEAPU8;let p=m._sda_rendered();
      for(let i=0;i<samples;i++)for(let c=0;c<2;c++,p+=3){const v=bytes[p]|bytes[p+1]<<8|bytes[p+2]<<16;reference[c]![i]=(v<<8>>8)/8388608;}
      this.referenceOnly(reference,rate);
      if(!this.emitSourcesWithReference){this.samplePos+=samples;return;}
    }

    const discard = this.samplePos + n <= this.discardBeforeSeconds * rate;
    let channels:Float32Array[],labels:string[],events:ObjectEvent[]=[],objectChannels:{id:number;channel:number}[]=[];
    if(objects){
      if(hoa)throw Error('MPEG-H mixed objects/HOA is not supported yet');
      const sourceBeds=Array.from({length:beds},(_,c)=>CICP_LABELS[m._sda_bed(c)]);
      if(sourceBeds.some(l=>!l))throw Error('MPEG-H unsupported bed geometry; refusing to invent object positions');
      const bedLabels=[...new Set(sourceBeds)] as string[];
      labels=[...bedLabels,...Array.from({length:objects},(_,i)=>`Obj_${i}`)];
      if(info(4)!==beds+objects)throw Error('MPEG-H source mapping mismatch');
      const p=m._sda_pcm()/4;
      channels=labels.map(()=>new Float32Array(discard ? 0 : n));
      for(let c=0;!discard && c<beds+objects;c++) {const target=c<beds?bedLabels.indexOf(sourceBeds[c]!):bedLabels.length+c-beds;
        for(let s=0;s<n;s++)channels[target]![s]+=m.HEAPF32[p+c*n+s];}
      objectChannels=Array.from({length:objects},(_,id)=>({id,channel:bedLabels.length+id}));
      const md=m.HEAPF32,base=m._sda_metadata()/4;
      for(let i=0;i<info(9);i++){
        const p=base+i*12,id=md[p],az=md[p+2]*Math.PI/180,el=md[p+3]*Math.PI/180;
        events.push({id,samplePos:this.samplePos+md[p+1],hasPos:true,
          pos:[-Math.sin(az)*Math.cos(el),Math.cos(az)*Math.cos(el),Math.sin(el)],
          gainDb:20*Math.log10(Math.max(1e-10,md[p+5])),
          size:[Math.min(1,md[p+6]/180),Math.min(1,md[p+8]),Math.min(1,md[p+7]/180)],
          diffuse:Math.max(0,Math.min(1,md[p+9])),anchor:md[p+10]?'screen':'room',
          // OAM radius is a relative renderer distance, not a measured metre value.
          distanceM:null,distanceInfinite:false,screenFactor:null,depthFactor:null,rampDuration:md[p+11]});
      }
      if(!events.length)throw Error('MPEG-H object PCM has no matching metadata');
    }else{
      // Channel / HOA programmes use the upstream stereo renderer, with zero objects.
      const count=info(11);n=info(10)/(count*3);
      if(!Number.isInteger(n)||count!==2)throw Error('MPEG-H unexpected stereo output');
      labels=['L','R'];channels=labels.map(()=>new Float32Array(discard ? 0 : n));
      const bytes=m.HEAPU8;let p=m._sda_rendered();
      for(let s=0;!discard && s<n;s++)for(let c=0;c<count;c++,p+=3){const v=bytes[p]|bytes[p+1]<<8|bytes[p+2]<<16;channels[c]![s]=(v<<8>>8)/8388608;}
    }
    this.frames.push({discardedSamples:discard?n:undefined,codec:'mpegh',sampleRate:rate,samplePos:this.samplePos,channels,labels,rawBedLabels:labels.filter(l=>!l.startsWith('Obj_')),events,objectChannels,programLoudness:null,rampDuration:0});
    this.samplePos+=n;
  }
  nextFrame():DecodedFrameData|null{return this.frames.shift()??null;}
  drainErrors():string[]{return [];}
  flush():void{if(this.pending.length)throw Error(`MPEG-H truncated stream (${this.pending.length} bytes remain)`);}
  free():void{if(!this.dead){runtime._sda_close();this.dead=true;this.frames=[];this.pending=new Uint8Array(0);}}
}
