import assert from 'node:assert/strict';
import {build} from 'esbuild';
const out=await build({entryPoints:['packages/player/src/seek-frame.ts'],bundle:true,format:'esm',write:false});
const {SeekFrameGate,SeekPacketGate}=await import(`data:text/javascript;base64,${Buffer.from(out.outputFiles[0].text).toString('base64')}`);
const event=(samplePos,pos)=>({id:7,samplePos,pos,hasPos:true,gainDb:-3,size:[0,0,0],anchor:'room',rampDuration:128});
const frame=(samplePos,events=[],rate=48000)=>({samplePos,sampleRate:rate,channels:[Float32Array.from({length:8},(_,i)=>samplePos+i)],events,objectChannels:[{id:7,channel:0}]});
const gate=new SeekFrameGate(12/48000);
assert.equal(gate.accept(frame(0,[event(0,[1,0,0])])),null);
const clipped=gate.accept(frame(8,[event(9,[0,1,0]),event(14,[0,0,1])]));
assert.equal(clipped.samplePos,12);assert.deepEqual([...clipped.channels[0]],[12,13,14,15]);
assert.deepEqual(clipped.events.map(e=>[e.samplePos,e.pos,e.rampDuration]),[[12,[0,1,0],0],[14,[0,0,1],128]]);
assert.deepEqual(gate.accept(frame(16)).channels[0],frame(16).channels[0]);
const held=new SeekFrameGate(8/48000);held.accept(frame(0,[event(0,[1,0,0])]));
assert.deepEqual(held.accept(frame(8)).events[0].pos,[1,0,0]);
const nativeRate=new SeekFrameGate(1);assert.equal(nativeRate.accept(frame(44090,[],44100)),null);
assert.equal(nativeRate.accept(frame(44098,[],44100)).samplePos,44100);
const restarted=new SeekFrameGate();const first=frame(0);assert.equal(restarted.accept(first),first);
console.log('seek gate: exact trim, retained object state, later events, sample rates and fresh start passed');
const packets=new SeekPacketGate(60);
packets.configure('mp4','ec-3',48000,48000);
assert.equal(packets.accept(56992),false);
assert.equal(packets.accept(57024),true);
const shifted=frame(0,[event(2,[1,0,0])]);
packets.restoreClock(shifted);
assert.equal(shifted.samplePos,2737152);
assert.equal(shifted.events[0].samplePos,2737154);
assert.equal(packets.accept(57056),true);
for (const [container,codec,rate] of [['mp4','mha1',48000],['raw','ec-3',48000],['mp4','ec-3',44100]]) {
  const fallback=new SeekPacketGate(60);fallback.configure(container,codec,rate,48000);
  assert.equal(fallback.accept(0),true);
  const original=frame(0);fallback.restoreClock(original);assert.equal(original.samplePos,0);
}
console.log('packet seek: preroll, absolute PCM/event clock and unsupported-codec fallback passed');
const alac=new SeekPacketGate(60);alac.configure('mp4','alac',44100,48000);
assert.equal(alac.accept(0),false);assert.equal(alac.accept(57000),true);
const sparse=new SeekFrameGate(1);
sparse.remember({...frame(0,[event(0,[1,0,0])]),discardedSamples:48000});
const resumed=sparse.accept({...frame(48000),objectChannels:[]});
assert.equal(resumed.objectChannels[0].id,7);assert.deepEqual(resumed.events[0].pos,[1,0,0]);
